insert into public.products (
  slug, name, description, category_id, brand_id,
  price, old_price, wholesale_price, flavors, image_path, image_alt,
  is_offer, is_out_of_stock, is_published, sort_order
)
select v.slug, v.name, v.description, c.id, b.id,
       v.price, v.old_price, v.wholesale_price, v.flavors, v.image_path, v.name,
       v.is_offer, v.is_out_of_stock, true, v.sort_order
from (values
  ('bcaa-2000-star-nutrition', 'BCAA 2000 Star Nutrition', 'Aminoácidos de cadena ramificada de alta pureza.', 'Aminoácidos', 'Star Nutrition', 15000, 18000, 12000, array['Neutro','Naranja']::text[], 'products/bcaa-2000-star-nutrition.webp', false, false, 10),
  ('carnitina-pro-ena', 'Carnitina Pro - ENA', 'L-Carnitina líquida para potenciar la quema de grasas.', 'Quemadores', 'ENA', 12000, 14500, 9500, array['Limón']::text[], 'products/carnitina-pro-ena.webp', true, false, 20),
  ('chia-pudding-granger-280g', 'Chia Pudding Granger 280g', 'Pudding de chía alto en proteína y bajo en carbohidratos.', 'Snacks', 'Granger', 4500, null::integer, 3500, array['Vainilla','Chocolate']::text[], 'products/chia-pudding-granger-280g.webp', false, false, 30),
  ('citrato-de-magnesio-ena', 'Citrato De Magnesio - ENA', 'Magnesio de alta asimilación para recuperación muscular.', 'Minerales', 'ENA', 8000, null::integer, 6500, '{}'::text[], 'products/citrato-de-magnesio-ena.webp', false, false, 40),
  ('citrato-de-magnesio-star-nutrition-60cap', 'Citrato De Magnesio - Star Nutrition 60cap', 'Magnesio en cápsulas para mejor descanso y recuperación.', 'Minerales', 'Star Nutrition', 8500, 9500, 6800, '{}'::text[], 'products/citrato-de-magnesio-star-nutrition-60cap.webp', true, false, 50),
  ('citrato-de-magnesio-x-body-120-caps', 'Citrato De Magnesio X-BODY 120 Caps', 'Magnesio de alta concentración, 120 cápsulas.', 'Minerales', 'X-BODY', 11000, null::integer, 8500, '{}'::text[], 'products/citrato-de-magnesio-x-body-120-caps.webp', false, false, 60),
  ('colageno-one-fit-240g', 'Colágeno One Fit 240g', 'Colágeno hidrolizado con vitamina C para articulaciones.', 'Colágeno', 'One Fit', 16000, null::integer, 12500, array['Naranja']::text[], 'products/colageno-one-fit-240g.webp', false, false, 70),
  ('colageno-plus-star-nutrition-360gr', 'Colágeno Plus Star Nutrition 360gr', 'Fórmula plus con ácido hialurónico y vitamina C.', 'Colágeno', 'Star Nutrition', 19500, 23000, 15000, array['Naranja']::text[], 'products/colageno-plus-star-nutrition-360gr.webp', true, false, 80),
  ('colageno-star-nutrition-210gr', 'Colágeno Star Nutrition 210gr', 'Colágeno hidrolizado puro, ideal para piel y articulaciones.', 'Colágeno', 'Star Nutrition', 14000, null::integer, 11000, '{}'::text[], 'products/colageno-star-nutrition-210gr.webp', false, false, 90),
  ('cookies-proteicas-granger', 'Cookies Proteicas Granger', 'Galletas altas en proteína, sin azúcar agregada.', 'Snacks', 'Granger', 3000, null::integer, 2200, array['Chips de Chocolate']::text[], 'products/cookies-proteicas-granger.webp', false, false, 100),
  ('creatina-ena-sabores-300g', 'Creatina ENA Sabores 300g', 'Creatina monohidrato saborizada, máxima pureza.', 'Creatinas', 'ENA', 21000, 24000, 17000, array['Fruit Punch','Uva']::text[], 'products/creatina-ena-sabores-300g.webp', true, false, 110),
  ('creatina-masticable-gomex-120-und', 'Creatina Masticable GOMEX 120 Und.', 'Creatina en gomitas masticables, fácil de tomar.', 'Creatinas', 'GOMEX', 18000, null::integer, 14000, array['Frutilla']::text[], 'products/creatina-masticable-gomex-120-und.webp', false, false, 120),
  ('creatina-masticable-gentech', 'Creatina Masticable Gentech', 'Creatina en tabletas masticables para llevar a todos lados.', 'Creatinas', 'Gentech', 15000, null::integer, 11500, array['Naranja']::text[], 'products/creatina-masticable-gentech.webp', false, false, 130),
  ('creatina-one-fit-200gr', 'Creatina One Fit 200gr', 'Creatina pura micronizada, 200g.', 'Creatinas', 'One Fit', 14000, null::integer, 10500, array['Neutro']::text[], 'products/creatina-one-fit-200gr.webp', false, false, 140),
  ('creatina-one-fit-500gr', 'Creatina One Fit 500gr', 'Creatina pura micronizada, formato ahorro 500g.', 'Creatinas', 'One Fit', 28000, 32000, 22000, array['Neutro']::text[], 'products/creatina-one-fit-500gr.webp', true, false, 150),
  ('creatina-star-nutrition-500g', 'Creatina Star Nutrition 500g', 'Creatina 100% pura y testeada, máxima calidad.', 'Creatinas', 'Star Nutrition', 30000, null::integer, 24000, array['Neutro']::text[], 'products/creatina-star-nutrition-500g.webp', false, false, 160),
  ('creatina-star-nutrition-doypack-300gr', 'Creatina Star Nutrition Doypack 300gr', 'Creatina en envase doypack, 300g.', 'Creatinas', 'Star Nutrition', 19000, null::integer, 15000, array['Neutro']::text[], 'products/creatina-star-nutrition-doypack-300gr.webp', false, false, 170),
  ('gel-energy-pont-43gr', 'Gel Energy Pont 43gr', 'Gel energético de rápida asimilación para deportes de resistencia.', 'Energía', 'Pont', 1500, null::integer, 1100, array['Limón','Manzana']::text[], 'products/gel-energy-pont-43gr.webp', false, false, 180),
  ('gelatina-granger-150g', 'Gelatina Granger 150g', 'Gelatina proteica sin azúcar.', 'Snacks', 'Granger', 3500, null::integer, 2600, array['Frutilla','Cereza']::text[], 'products/gelatina-granger-150g.webp', false, false, 190),
  ('glisinato-magnesio-gold', 'Glisinato Magnesio Gold', 'Glicinato de magnesio de alta absorción.', 'Minerales', 'Gold', 12500, 14000, 9500, '{}'::text[], 'products/glisinato-magnesio-gold.webp', true, false, 200),
  ('multivitaminico-one-fit-60-cap', 'Multivitamínico One Fit 60 cap', 'Complejo multivitamínico completo diario.', 'Vitaminas', 'One Fit', 7500, null::integer, 5500, '{}'::text[], 'products/multivitaminico-one-fit-60-cap.webp', false, false, 210),
  ('nad-gold', 'NAD+ Gold', 'Suplemento antienvejecimiento y energía celular NAD+.', 'Vitaminas', 'Gold', 25000, null::integer, 19000, '{}'::text[], 'products/nad-gold.webp', false, false, 220),
  ('nutremax-hydromax-660g', 'Nutremax - Hydromax 660g', 'Bebida isotónica para hidratación profunda.', 'Energía', 'Nutremax', 14000, 16500, 10500, array['Naranja','Limón']::text[], 'products/nutremax-hydromax-660g.webp', true, false, 230),
  ('omega-3-star-nutrition', 'Omega 3 Star Nutrition', 'Aceite de pescado rico en EPA y DHA.', 'Vitaminas', 'Star Nutrition', 11000, null::integer, 8500, '{}'::text[], 'products/omega-3-star-nutrition.webp', false, false, 240),
  ('omelette-proteico-granger', 'Omelette Proteico Granger', 'Preparado para omelette alto en proteínas.', 'Snacks', 'Granger', 5500, null::integer, 4200, array['Queso']::text[], 'products/omelette-proteico-granger.webp', false, false, 250),
  ('pancakes-keto-granger', 'Pancakes KETO Granger', 'Premezcla para pancakes keto, bajos en carbohidratos.', 'Snacks', 'Granger', 6000, null::integer, 4500, array['Vainilla']::text[], 'products/pancakes-keto-granger.webp', false, false, 260),
  ('pancakes-proteicos-mole-450gr', 'Pancakes Proteicos MOLE 450gr', 'Mix para panqueques proteicos súper esponjosos.', 'Snacks', 'MOLE', 7500, 9000, 5800, array['Vainilla','Chocolate']::text[], 'products/pancakes-proteicos-mole-450gr.webp', true, false, 270),
  ('proteina-one-fit-2lb', 'Proteína One Fit 2lb', 'Whey Protein concentrado de alta calidad, 2lb.', 'Proteínas', 'One Fit', 22000, null::integer, 17500, array['Vainilla','Chocolate','Frutilla']::text[], 'products/proteina-one-fit-2lb.webp', false, false, 280),
  ('proteina-star-nutrition-2lb', 'Proteína Star Nutrition 2lb', 'Proteína de suero premium. Excelente sabor y disolución.', 'Proteínas', 'Star Nutrition', 29000, 34000, 23000, array['Vainilla','Chocolate','Cookies & Cream']::text[], 'products/proteina-star-nutrition-2lb.webp', true, false, 290),
  ('proteina-vegetal-gold-2lb', 'Proteína Vegetal Gold 2lb', 'Blend de proteínas vegetales de alta digestibilidad.', 'Proteínas', 'Gold', 25000, null::integer, 19500, array['Vainilla','Chocolate']::text[], 'products/proteina-vegetal-gold-2lb.webp', false, false, 300),
  ('pure-proteico-granger-150g', 'Puré Proteico Granger 150g', 'Puré de papas instantáneo enriquecido con proteína.', 'Snacks', 'Granger', 4000, null::integer, 3000, array['Original']::text[], 'products/pure-proteico-granger-150g.webp', false, false, 310),
  ('resveratrol-500-star-nutrition', 'Resveratrol 500 Star Nutrition', 'Potente antioxidante natural.', 'Vitaminas', 'Star Nutrition', 13000, 15000, 10000, '{}'::text[], 'products/resveratrol-500-star-nutrition.webp', true, false, 320),
  ('salsa-mrs-taste', 'Salsa Mrs Taste', 'Salsas cero calorías y cero sodio para tus comidas.', 'Snacks', 'Mrs Taste', 4500, null::integer, 3400, array['Ketchup','Barbacoa','Mostaza']::text[], 'products/salsa-mrs-taste.webp', false, false, 330),
  ('thermo-fuel-max-star-nutrition', 'Thermo Fuel Max - Star Nutrition', 'Termogénico potente para máxima definición.', 'Quemadores', 'Star Nutrition', 16000, null::integer, 12500, '{}'::text[], 'products/thermo-fuel-max-star-nutrition.webp', false, false, 340),
  ('vitamina-c-one-fit', 'Vitamina C - One Fit', 'Vitamina C 1000mg para fortalecer el sistema inmune.', 'Vitaminas', 'One Fit', 5500, null::integer, 4000, array['Naranja']::text[], 'products/vitamina-c-one-fit.webp', false, false, 350),
  ('vitamina-c-star-nutrition', 'Vitamina C Star Nutrition', 'Vitamina C con rosa mosqueta de alta absorción.', 'Vitaminas', 'Star Nutrition', 6500, null::integer, 5000, '{}'::text[], 'products/vitamina-c-star-nutrition.webp', false, false, 360),
  ('vitamina-d3-k2-one-fit-60-cap', 'Vitamina D3 + K2 One Fit 60 cap', 'Combo ideal para la salud ósea e inmunológica.', 'Vitaminas', 'One Fit', 8500, 10000, 6500, '{}'::text[], 'products/vitamina-d3-k2-one-fit-60-cap.webp', true, false, 370),
  ('pancakes-proteicos-granger-400gr', 'Pancakes Proteicos Granger 400gr', 'Deliciosos panqueques proteicos fáciles de preparar.', 'Snacks', 'Granger', 7000, null::integer, 5500, array['Vainilla']::text[], 'products/pancakes-proteicos-granger-400gr.webp', false, false, 380),
  ('cupcakes-proteicos-granger', 'Cupcakes Proteicos Granger', 'Preparado para muffins/cupcakes altos en proteína.', 'Snacks', 'Granger', 6000, null::integer, 4500, array['Chocolate']::text[], 'products/cupcakes-proteicos-granger.webp', false, false, 390),
  ('ultratech-pudding-proteico-400g', 'UltraTech Pudding Proteico 400g', 'Postre proteico bajo en grasas, exquisito sabor.', 'Snacks', 'UltraTech', 8000, 9500, 6000, array['Vainilla','Chocolate']::text[], 'products/ultratech-pudding-proteico-400g.webp', true, false, 400)
) as v(slug, name, description, category_name, brand_name,
       price, old_price, wholesale_price, flavors, image_path,
       is_offer, is_out_of_stock, sort_order)
join public.categories c on c.name = v.category_name
join public.brands     b on b.name = v.brand_name
on conflict (slug) do update set
  name = excluded.name, description = excluded.description,
  category_id = excluded.category_id, brand_id = excluded.brand_id,
  price = excluded.price, old_price = excluded.old_price,
  wholesale_price = excluded.wholesale_price, flavors = excluded.flavors,
  image_path = excluded.image_path, image_alt = excluded.image_alt,
  is_offer = excluded.is_offer,
  is_out_of_stock = excluded.is_out_of_stock, sort_order = excluded.sort_order;
